### ISSUE TITLE
S3ResponseError: 403 Forbidden SignatureDoesNotMatch

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-attachment#143]
When upload attachment to S3:

```
S3ResponseError: S3ResponseError: 403 Forbidden
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><AWSAccessKeyId>AXXXXXXXXXXXXX</AWSAccessKeyId><StringToSign>PUT
+Rd+zB/EPrYCamVPX0VsrA==
image/png,image/png
Thu, 26 Jul 2018 11:21:08 GMT
x-amz-acl:public-read
x-amz-security-token:XXXXXXXX
/net-mozaws-stage-kinto-fennec/main-workspace/product-integrity/176b096a-2980-49a9-845b-479900c9f9a2.png</StringToSign><SignatureProvided>XXXXXXXXXXXXXXXXMK5pw=</SignatureProvided><StringToSignBytes>50 55 54 0a 2b 52 64 2b 7a 42 2f 45 50 72 59 43 61 6d 56 50 58 30 56 73 72 41 3d 3d 0a 69 6d 61 67 65 2f 70 6e 67 2c 69 6d 61 67 65 2f 70 6e 67 0a 54 68 75 2c 20 32 36 20 4a 75 6c 20 32 30 31 38 20 31 31 3a 32 31 3a 30 38 20 47 4d 54 0a 78 2d 61 6d 7a 2d 61 63 6c 3a 70 75 62 6c 69 63 2d 72 65 61 64 0a 78 2d 61 6d 7a 2d 73 65 63 75 72 69 74 79 2d 74 6f 6b 65 6e 3a 46 51 6f 44 59 58 64 7a 45 4b 54 2f 2f 2f 2f 2f 2f 2f 2f 2f 2f 77 45 61 44 46 43 46 43 58 61 42 38 4d 59 37 49 4b...
```

Probably due to https://github.com/Kinto/kinto-attachment/pull/140

**Comment by glasserc** [comment]
As I wrote in https://bugzilla.mozilla.org/show_bug.cgi?id=1478622, there seems to be a chain of failures here:

- `pyramid_storage` uses boto instead of boto3
- pyramid_storage sets a `Content-Type` on the key as well as passing along the `content-type` we set
- boto appears to send both even though headers are case-insensitive
- Amazon appears to use both `Content-Type` and `content-type` when trying to calculate a signature, though boto uses only one

The "true" fix is probably to stop setting a `content-type` header, since it's redundant with the `Content-Type` header that boto adds for us. However, #145 gets rid of this whole code path, so we may as well do that.
